### ISSUE TITLE
Works with Pi OS, but not with Ubuntu

### ISSUE THREAD

**Issue by kilrau** [tux1c/wavesharelcd-64bit-rpi#3]
Good stuff! This gets [this 3.5" GPIO display]( http://www.lcdwiki.com/3.5inch_RPi_Display) working on the [latest 64bit Pi OS](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/), but I had to comment out quite some more pi-os-default-enabled options in `/boot/config`.

Original `/boot/config` after fresh installation of Pi OS 64bit (LCD **not** working):
```
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
arm_64bit=1
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=waveshare35a:rotate=90
```

Modified (LCD working :tada: ):
```
#dtoverlay=vc4-fkms-v3d
#max_framebuffers=2
arm_64bit=1
#hdmi_force_hotplug=1
#dtparam=i2c_arm=on
#dtparam=spi=on
#enable_uart=1
dtoverlay=waveshare35a:rotate=90
```
Commenting out `dtoverlay=vc4-fkms-v3d` only as per README was not enough. With only this commented out and the rest all enabled, the lcd would show some cli output on boot, but then go black.

On the latest [64bit ubuntu](https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04.1&architecture=arm64+raspi) I could **not** find a `/boot/config` configuration to get the display working.

Original `/boot/config`after fresh installation of Ubuntu Server 20.04.01 64bit (LCD **not** working):
```
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
arm_64bit=1
dtoverlay=waveshare35a:rotate=90
```

Tried several modifications like this one, but LCD not working:
```
#hdmi_force_hotplug=1
#dtparam=i2c_arm=on
#dtparam=spi=on
#enable_uart=1
arm_64bit=1
dtoverlay=waveshare35a:rotate=90
```

**Comment by kilrau** [comment]
Noticed this difference in the resulting `/boot/config.txt` after installation of this driver:
Pi OS:
```
max_framebuffers=2
arm_64bit=1
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=waveshare35a:rotate=90
```

ubuntu:
```
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
dtoverlay=waveshare35a:rotate=90
```

**Comment by kilrau** [comment]
`#hdmi_force_hotplug=1` is the culprit. Commenting out this together with `dtoverlay=vc4-fkms-v3d` is enough to get all up and working just fine. Here my complete /boot/config.txt which is working fine:
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2
arm_64bit=1
#hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=waveshare35a:rotate=90
```

**Comment by nofacer** [comment]
@kilrau HI, which pi do you use. Is that Pi4B?

**Comment by kilrau** [comment]
> Is that Pi4B?

Yes.

**Comment by uplusion23** [comment]
Matched config posted above, installed the drivers on the x64 raspbian, but still getting a white screen. I've tried prebuild images for the MHS35 but has always been a white screen. Any ideas?

**Comment by tobiasKurz1** [comment]
Did anyone get this working on a newer Raspberry PI OS image? Tried using the OS posted above but my Pi is not compatible with this old version. @kilrau did you try a newer image later on?
Newest version of PI OS does not work, even after trying all of the configurations.

**Comment by kilrau** [comment]
No. I am not running any Pis anymore, so consider this outdated.

**Comment by tobiasKurz1** [comment]
For anyone finding this still looking for a solution: I got it running fine on a Pi 4B with a earlier Version of Pi OS (2021-10-30-raspios-bullseye-arm64). My display is waveshare 3.5A. Still works after updating even without changing the config file. Just make sure you apply [this fix](https://github.com/tux1c/wavesharelcd-64bit-rpi/pull/4).
May be possible to work with later versions but have not tried.
